// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_CV.Data;

#nullable disable

namespace WEB_CV.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20250821124625_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_CV.Models.BaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuyenMucId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenMucId");

                    b.HasIndex("TacGiaId");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("WEB_CV.Models.BaiVietTag", b =>
                {
                    b.Property<int>("BaiVietId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BaiVietId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BaiVietTags");
                });

            modelBuilder.Entity("WEB_CV.Models.BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiVietId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaiVietId");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("WEB_CV.Models.ChuyenMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChuyenMucs");
                });

            modelBuilder.Entity("WEB_CV.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("WEB_CV.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("WEB_CV.Models.BaiViet", b =>
                {
                    b.HasOne("WEB_CV.Models.ChuyenMuc", "ChuyenMuc")
                        .WithMany("BaiViets")
                        .HasForeignKey("ChuyenMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WEB_CV.Models.NguoiDung", "TacGia")
                        .WithMany("BaiViets")
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuyenMuc");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("WEB_CV.Models.BaiVietTag", b =>
                {
                    b.HasOne("WEB_CV.Models.BaiViet", "BaiViet")
                        .WithMany("BaiVietTags")
                        .HasForeignKey("BaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB_CV.Models.Tag", "Tag")
                        .WithMany("BaiVietTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WEB_CV.Models.BinhLuan", b =>
                {
                    b.HasOne("WEB_CV.Models.BaiViet", "BaiViet")
                        .WithMany("BinhLuans")
                        .HasForeignKey("BaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");
                });

            modelBuilder.Entity("WEB_CV.Models.BaiViet", b =>
                {
                    b.Navigation("BaiVietTags");

                    b.Navigation("BinhLuans");
                });

            modelBuilder.Entity("WEB_CV.Models.ChuyenMuc", b =>
                {
                    b.Navigation("BaiViets");
                });

            modelBuilder.Entity("WEB_CV.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");
                });

            modelBuilder.Entity("WEB_CV.Models.Tag", b =>
                {
                    b.Navigation("BaiVietTags");
                });
#pragma warning restore 612, 618
        }
    }
}
